# Production-Ready GitLab CI/CD Pipeline
image: docker:24.0.5

stages:
  - validate
  - build
  - test
  - security
  - push
  - deploy-staging
  - deploy-production

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_IMAGE_NAME: docker-cicd-demo
  STAGING_PORT: 8081
  PRODUCTION_PORT: 8080

services:
  - docker:24.0.5-dind

# Global before script
before_script:
  - docker --version
  - docker info
  - echo "Pipeline triggered by $GITLAB_USER_NAME for commit $CI_COMMIT_SHORT_SHA"

# Validate stage - Check code quality
validate_code:
  stage: validate
  script:
    - echo "🔍 Validating code structure..."
    - test -f Dockerfile || (echo "❌ Dockerfile missing" && exit 1)
    - test -f package.json || (echo "❌ package.json missing" && exit 1)
    - test -f app.js || (echo "❌ app.js missing" && exit 1)
    - echo "✅ Code validation passed"
  only:
    - main
    - develop
    - merge_requests

# Build stage
build_images:
  stage: build
  script:
    - echo "🏗️ Building Docker images..."
    - docker build -t $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker build -t $DOCKER_IMAGE_NAME:latest .
    - docker build -f Dockerfile.test -t $DOCKER_IMAGE_NAME:test . || docker build -t $DOCKER_IMAGE_NAME:test .
    - docker images | grep $DOCKER_IMAGE_NAME
    - echo "✅ Images built successfully"
  artifacts:
    expire_in: 1 hour
    reports:
      dotenv: build.env
  only:
    - main
    - develop
    - merge_requests

# Test stage - Comprehensive testing
run_tests:
  stage: test
  script:
    - echo "🧪 Running comprehensive test suite..."
    - echo "Starting application container..."
    - docker run -d --name test-app -p 3000:3000 $DOCKER_IMAGE_NAME:latest
    - sleep 20
    - echo "Running health checks..."
    - docker exec test-app curl -f http://localhost:3000/
scan_image:
  stage: security
  image: aquasec/trivy:latest
  script:
    - echo "🔒 Scanning Docker image for vulnerabilities..."
    - trivy image --severity HIGH,CRITICAL $DOCKER_IMAGE_NAME:latest || true
    - echo "✅ Security scan complete"
  only:
    - main
    - develop
