version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300

  chrome-node:
    image: selenium/node-chrome:4.15.0
    container_name: chrome-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=4
      - NODE_MAX_SESSION=4
    ports:
      - "7900:7900"
    volumes:
      - ./screenshots:/home/seluser/screenshots

  firefox-node:
    image: selenium/node-firefox:4.15.0
    container_name: firefox-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
    ports:
      - "7901:7900"

  test-runner:
    build: .
    container_name: test-runner
    depends_on:
      - selenium-hub
      - chrome-node
    volumes:
      - ./tests:/app/tests
      - ./reports:/app/reports
      - ./screenshots:/app/screenshots
    environment:
      - SELENIUM_HUB_URL=http://selenium-hub:4444/wd/hub
    command: ["pytest", "tests/", "-v", "--html=reports/test_report.html"]