version: '3.8'

services:
  mpi-master:
    image: hpc-base:latest
    container_name: mpi-master
    hostname: mpi-master
    networks:
      - mpi-network
    volumes:
      - .:/hpc
      - mpi-shared:/shared
    command: tail -f /dev/null
    environment:
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

  mpi-worker1:
    image: hpc-base:latest
    container_name: mpi-worker1
    hostname: mpi-worker1
    networks:
      - mpi-network
    volumes:
      - .:/hpc
      - mpi-shared:/shared
    command: tail -f /dev/null
    environment:
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

  mpi-worker2:
    image: hpc-base:latest
    container_name: mpi-worker2
    hostname: mpi-worker2
    networks:
      - mpi-network
    volumes:
      - .:/hpc
      - mpi-shared:/shared
    command: tail -f /dev/null
    environment:
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

networks:
  mpi-network:
    driver: bridge

volumes:
  mpi-shared: