version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.secure
    ports:
      - "3000:3000"
    restart: unless-stopped
    
    # Security configurations
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    
    # Capabilities
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    
    # Security options
    security_opt:
      - no-new-privileges:true
      - apparmor:docker-default
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
    
    # User namespace
    user: "1001:1001"
    
    # Environment
    environment:
      - NODE_ENV=production
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"