version: '3.8'

services:
  web:
    build: .
    container_name: flask-web-app
    ports:
      - "8080:5000"
    volumes:
      - app-data:/app/data
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///app/data/visitors.db
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: flask-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: flask-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app-network
    restart: unless-stopped

volumes:
  app-data:
    driver: local
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge