version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: frontend-web
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true