version: '3.8'

services:
  web:
    build: ./web-app
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=staging
      - DATABASE_URL=postgresql://postgres:staging123@db:5432/stagingdb
    depends_on:
      - db
    networks:
      - staging-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=stagingdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=staging123
    volumes:
      - staging-postgres-data:/var/lib/postgresql/data
    networks:
      - staging-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - staging-network

networks:
  staging-network:
    driver: bridge

volumes:
  staging-postgres-data:
    driver: local