version: '3.8'

services:
  blue-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: blue-app
    volumes:
      - ./app/blue:/app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - APP_VERSION=blue
    networks:
      - blue-green-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  blue-green-network:
    driver: bridge
    name: blue-green-network