version: '3.8'

services:
  green-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: green-app
    volumes:
      - ./app/green:/app
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - APP_VERSION=green
    networks:
      - blue-green-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  blue-green-network:
    external: true