version: '3.8'

services:
  nginx-lb:
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - blue-green-network
    restart: unless-stopped
    depends_on:
      - blue-app
      - green-app
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  blue-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: blue-app
    volumes:
      - ./app/blue:/app
    environment:
      - NODE_ENV=production
      - APP_VERSION=blue
    networks:
      - blue-green-network
    restart: unless-stopped

  green-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: green-app
    volumes:
      - ./app/green:/app
    environment:
      - NODE_ENV=production
      - APP_VERSION=green
    networks:
      - blue-green-network
    restart: unless-stopped

networks:
  blue-green-network:
    driver: bridge