version: '3.8'

services:
  jobmanager:
    image: flink:1.18-scala_2.12
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - FLINK_PROPERTIES=jobmanager.rpc.address:jobmanager
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./jobs:/opt/flink/jobs
      - ./logs:/opt/flink/log
      - ./data:/opt/flink/data
    networks:
      - flink-network
    restart: unless-stopped

  taskmanager1:
    image: flink:1.18-scala_2.12
    container_name: flink-taskmanager1
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - FLINK_PROPERTIES=jobmanager.rpc.address:jobmanager
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2
    volumes:
      - ./jobs:/opt/flink/jobs
      - ./logs:/opt/flink/log
      - ./data:/opt/flink/data
    networks:
      - flink-network
    restart: unless-stopped

  taskmanager2:
    image: flink:1.18-scala_2.12
    container_name: flink-taskmanager2
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - FLINK_PROPERTIES=jobmanager.rpc.address:jobmanager
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2
    volumes:
      - ./jobs:/opt/flink/jobs
      - ./logs:/opt/flink/log
      - ./data:/opt/flink/data
    networks:
      - flink-network
    restart: unless-stopped

networks:
  flink-network:
    driver: bridge